import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrimaryNav from "./_components/primary-nav";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import TRPCQueryProvider from "./_trpc/provider";
// import TanstackProvider from './_providers/TanstackProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TRPCQueryProvider>
          <PrimaryNav />
          {children}
        </TRPCQueryProvider>
      </body>
    </html>
  );
}
